name: Build & Publish BlobPE to GitHub Packages (Manual Only/Main)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.PACKAGE_TOKEN_GITHUB }}

      - name: Verify BlobPE publication on GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN_GITHUB }}
          OWNER: ${{ github.repository_owner }}
        run: |
          VERSION=$(ls ./nupkg/BlobPE.*.nupkg | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "Vérification de BlobPE version $VERSION sur GitHub Packages pour $OWNER"
          sleep 15 # Attendre l'indexation côté GitHub
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/users/$OWNER/packages/nuget/BlobPE/versions")
          if echo "$RESPONSE" | grep -q "\"name\": \"$VERSION\""; then
            echo "BlobPE $VERSION trouvé sur GitHub Packages !"
          else
            echo "BlobPE $VERSION introuvable sur GitHub Packages !"
            exit 1
          fi
