name: Build & Publish NuGet Package (Manual Only/Main)

on:
  workflow_dispatch: # Jamais automatique

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # S'assure que c'est sur main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Mets ici la version cible si besoin

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.PACKAGE_TOKEN_GITHUB }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key ${{ secrets.PACKAGE_TOKEN_NUGET }}
